### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by princerachit**
# What and why?

Fix typo `endoints` -> `endpoints`

# Testing Steps

Please provide adequate testing steps (including screenshots if necessary).
Include any test fixtures or sample configurations in your commit.

- [ ] Added unit tests for this feature (`make test`)

# Reviewers

Required reviewers: `@byxorna`
Request reviews from other people you want to review this PR in the "Reviewers" section on the right.

> :warning: this PR must have at least 2 thumbs from the [MAINTAINERS.md](/MAINTAINERS.md) of the project before merging!

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by princerachit** [comment]
> Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! 😄

Says internal server error

**Comment by byxorna** [comment]
@princerachit thanks for the PR! I am able to hit https://yahoocla.herokuapp.com/ just fine - can you give the CLA another peek now?

**Comment by princerachit** [comment]
@byxorna fixed

**Comment by byxorna** [comment]
@princerachit thanks!

**Pull request merged**
